services:
  api-router:
    build: .
    ports:
      - "80:80"
      - "443:443"
    environment:
      - OR_MODEL=${OR_MODEL}
      - OR_KEY=${OR_KEY}
      - OR_ENDPOINT=${OR_ENDPOINT}
    networks:
      - router-net

networks:
  router-net:
    driver: bridge
